(() => {
'use strict';
const W=64,H=64,PIX=W*H;
const $=id=>document.getElementById(id);
const state={
  source:null, sourceName:'', sourceRGBA:null, cutRGBA:null, mask:null,
  palette:['#1b1f2a','#4b4968','#77749b','#b8b5d2','#f2d5c7','#d69c80','#735247','#133d31','#1f6647','#75a77d','#cfe6bd','#d69b2d','#f2c95f','#0c171b','#273c43','#ffffff'],
  colorIndex:4, tool:'pen', brush:1, zoom:8, layers:[], activeLayer:0,
  undo:[], redo:[], drawing:false, start:null, last:null, frames:[], workflow:new Set(),
  projectName:'sprite_project'
};
const C={composite:$('compositeCanvas'),editor:$('editorCanvas'),grid:$('gridCanvas'),mask:$('maskPreview'),cut:$('cutPreview'),pal:$('palettePreview'),out32:$('out32'),out64:$('out64'),out128:$('out128')};
const ctx={comp:C.composite.getContext('2d'),edit:C.editor.getContext('2d'),grid:C.grid.getContext('2d'),mask:C.mask.getContext('2d'),cut:C.cut.getContext('2d'),pal:C.pal.getContext('2d')};
Object.values(ctx).forEach(c=>{c.imageSmoothingEnabled=false;});
function log(s){$('status').textContent='['+new Date().toLocaleTimeString()+'] '+s+'\n'+$('status').textContent.slice(0,2500)}
function mark(step){state.workflow.add(step); document.querySelectorAll('.step').forEach(e=>e.classList.toggle('done',state.workflow.has(e.dataset.step)));}
function rgba(hex,a=255){const h=hex.replace('#','');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),a]}
function hex(r,g,b){return '#'+[r,g,b].map(v=>Math.max(0,Math.min(255,v|0)).toString(16).padStart(2,'0')).join('')}
function blank(name='新規レイヤー'){return {id:crypto.randomUUID?.()||String(Date.now()+Math.random()),name,visible:true,data:new Uint8ClampedArray(PIX*4)}}
function addLayer(name,activate=true){state.layers.push(blank(name)); if(activate)state.activeLayer=state.layers.length-1; renderLayers(); renderAll(); return state.layers[state.layers.length-1];}
function ensureLayers(){if(!state.layers.length){['影','素体','後ろ髪','衣装','袖','顔','耳','前髪','装飾'].forEach(n=>addLayer(n,false));state.activeLayer=5;renderLayers();}}
function snapshot(){const snap={active:state.activeLayer,layers:state.layers.map(l=>({name:l.name,visible:l.visible,data:Array.from(l.data)}))};state.undo.push(snap);if(state.undo.length>25)state.undo.shift();state.redo=[];}
function restore(s){state.layers=s.layers.map((l,i)=>({id:String(i)+'-'+Date.now(),name:l.name,visible:l.visible,data:new Uint8ClampedArray(l.data)}));state.activeLayer=Math.min(s.active,state.layers.length-1);renderLayers();renderAll();}
function doUndo(){if(!state.undo.length)return;const cur={active:state.activeLayer,layers:state.layers.map(l=>({name:l.name,visible:l.visible,data:Array.from(l.data)}))};state.redo.push(cur);restore(state.undo.pop());}
function doRedo(){if(!state.redo.length)return;const cur={active:state.activeLayer,layers:state.layers.map(l=>({name:l.name,visible:l.visible,data:Array.from(l.data)}))};state.undo.push(cur);restore(state.redo.pop());}
function put(layer,x,y,c){if(x<0||y<0||x>=W||y>=H)return;const i=(y*W+x)*4;layer.data.set(c,i)}
function get(layer,x,y){if(x<0||y<0||x>=W||y>=H)return [0,0,0,0];const i=(y*W+x)*4;return Array.from(layer.data.slice(i,i+4))}
function paint(x,y,c,layer=state.layers[state.activeLayer]){const b=state.brush;const r=Math.floor((b-1)/2);for(let yy=y-r;yy<y-r+b;yy++)for(let xx=x-r;xx<x-r+b;xx++)put(layer,xx,yy,c)}
function line(x0,y0,x1,y1,c,layer=state.layers[state.activeLayer]){let dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,err=dx+dy;for(;;){paint(x0,y0,c,layer);if(x0===x1&&y0===y1)break;const e=2*err;if(e>=dy){err+=dy;x0+=sx}if(e<=dx){err+=dx;y0+=sy}}}
function rect(x0,y0,x1,y1,c,layer=state.layers[state.activeLayer]){const a=Math.min(x0,x1),b=Math.max(x0,x1),d=Math.min(y0,y1),e=Math.max(y0,y1);for(let x=a;x<=b;x++){paint(x,d,c,layer);paint(x,e,c,layer)}for(let y=d;y<=e;y++){paint(a,y,c,layer);paint(b,y,c,layer)}}
function flood(x,y,c){const l=state.layers[state.activeLayer],t=get(l,x,y);if(t.every((v,i)=>v===c[i]))return;const q=[[x,y]],seen=new Uint8Array(PIX);while(q.length){const [px,py]=q.pop();if(px<0||py<0||px>=W||py>=H)continue;const p=py*W+px;if(seen[p])continue;seen[p]=1;const v=get(l,px,py);if(!v.every((n,i)=>n===t[i]))continue;put(l,px,py,c);q.push([px+1,py],[px-1,py],[px,py+1],[px,py-1]);}}
function composite(){const out=new Uint8ClampedArray(PIX*4);for(const l of state.layers){if(!l.visible)continue;for(let i=0;i<PIX;i++){const j=i*4,a=l.data[j+3]/255;if(!a)continue;const da=out[j+3]/255,oa=a+da*(1-a);if(!oa)continue;out[j]=(l.data[j]*a+out[j]*da*(1-a))/oa;out[j+1]=(l.data[j+1]*a+out[j+1]*da*(1-a))/oa;out[j+2]=(l.data[j+2]*a+out[j+2]*da*(1-a))/oa;out[j+3]=oa*255;}}return out}
function drawData(canvas,data,w=W,h=H){const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,canvas.width,canvas.height);const im=new ImageData(new Uint8ClampedArray(data),w,h);const t=document.createElement('canvas');t.width=w;t.height=h;t.getContext('2d').putImageData(im,0,0);c.drawImage(t,0,0,canvas.width,canvas.height)}
function renderAll(){const d=composite();ctx.comp.putImageData(new ImageData(d,W,H),0,0);ctx.edit.clearRect(0,0,W,H);renderGrid();refreshOutputs(false)}
function renderGrid(){ctx.grid.clearRect(0,0,W,H);if(!$('gridToggle').checked)return;ctx.grid.strokeStyle='rgba(255,255,255,.17)';ctx.grid.lineWidth=.08;for(let i=0;i<=64;i++){ctx.grid.beginPath();ctx.grid.moveTo(i,0);ctx.grid.lineTo(i,64);ctx.grid.stroke();ctx.grid.beginPath();ctx.grid.moveTo(0,i);ctx.grid.lineTo(64,i);ctx.grid.stroke()}}
function renderLayers(){$('layers').innerHTML='';[...state.layers].reverse().forEach((l,ri)=>{const i=state.layers.length-1-ri,el=document.createElement('div');el.className='layer'+(i===state.activeLayer?' active':'');el.innerHTML=`<button class="eye">${l.visible?'👁':'—'}</button><div class="layerName"></div><button class="up">↑</button><button class="del">×</button>`;el.querySelector('.layerName').textContent=l.name;el.querySelector('.layerName').onclick=()=>{state.activeLayer=i;renderLayers()};el.querySelector('.eye').onclick=()=>{l.visible=!l.visible;renderLayers();renderAll()};el.querySelector('.up').onclick=()=>{if(i<state.layers.length-1){snapshot();[state.layers[i],state.layers[i+1]]=[state.layers[i+1],state.layers[i]];state.activeLayer=i+1;renderLayers();renderAll()}};el.querySelector('.del').onclick=()=>{if(state.layers.length>1){snapshot();state.layers.splice(i,1);state.activeLayer=Math.min(state.activeLayer,state.layers.length-1);renderLayers();renderAll()}};$('layers').append(el)})}
function renderPalette(){$('palette').innerHTML='';state.palette.forEach((c,i)=>{const b=document.createElement('button');b.className='swatch'+(i===state.colorIndex?' active':'');b.style.background=c;b.title=c;b.onclick=()=>{state.colorIndex=i;$('colorPicker').value=c;renderPalette()};$('palette').append(b)});drawPalettePreview()}
function drawPalettePreview(){ctx.pal.clearRect(0,0,128,128);const cols=4,s=32;state.palette.slice(0,16).forEach((c,i)=>{ctx.pal.fillStyle=c;ctx.pal.fillRect((i%cols)*s,Math.floor(i/cols)*s,s,s)})}
function pointerPos(e){const r=C.editor.getBoundingClientRect();return [Math.max(0,Math.min(63,Math.floor((e.clientX-r.left)/r.width*64))),Math.max(0,Math.min(63,Math.floor((e.clientY-r.top)/r.height*64)))]}
function onDown(e){e.preventDefault();C.editor.setPointerCapture?.(e.pointerId);state.drawing=true;state.start=state.last=pointerPos(e);snapshot();const [x,y]=state.start;const col=state.tool==='eraser'?[0,0,0,0]:rgba(state.palette[state.colorIndex]);if(state.tool==='fill'){flood(x,y,col);state.drawing=false;renderAll()}else if(state.tool==='picker'){const c=get(state.layers[state.activeLayer],x,y);if(c[3]){const h=hex(...c);let i=state.palette.indexOf(h);if(i<0){state.palette.push(h);i=state.palette.length-1}state.colorIndex=i;renderPalette()}state.drawing=false}else if(['pen','eraser'].includes(state.tool)){paint(x,y,col);renderAll()}}
function onMove(e){const [x,y]=pointerPos(e);$('cursorInfo').textContent=`x:${x}, y:${y}`;if(!state.drawing||!['pen','eraser'].includes(state.tool))return;const col=state.tool==='eraser'?[0,0,0,0]:rgba(state.palette[state.colorIndex]);line(state.last[0],state.last[1],x,y,col);state.last=[x,y];renderAll()}
function onUp(e){if(!state.drawing)return;const p=pointerPos(e),col=state.tool==='eraser'?[0,0,0,0]:rgba(state.palette[state.colorIndex]);if(state.tool==='line')line(...state.start,...p,col);if(state.tool==='rect')rect(...state.start,...p,col);state.drawing=false;renderAll();mark('pixel')}
function loadImage(file){const url=URL.createObjectURL(file),im=new Image();im.onload=()=>{state.source=im;state.sourceName=file.name;state.projectName=file.name.replace(/\.[^.]+$/,'')+'_sprite';$('sourceImage').src=url;$('sourceInfo').textContent=`${im.naturalWidth}×${im.naturalHeight}`;const cv=document.createElement('canvas');cv.width=im.naturalWidth;cv.height=im.naturalHeight;const c=cv.getContext('2d',{willReadFrequently:true});c.drawImage(im,0,0);state.sourceRGBA=c.getImageData(0,0,cv.width,cv.height);mark('input');extractPalette();log('画像を読み込みました')};im.src=url}
function colorDist(a,b){return Math.sqrt((a[0]-b[0])**2+(a[1]-b[1])**2+(a[2]-b[2])**2)}
function autoCut(){if(!state.sourceRGBA){log('先に画像を読み込んでください');return}const im=state.sourceRGBA,w=im.width,h=im.height,d=im.data,t=+$('bgTolerance').value;const cs=[[2,2],[w-3,2],[2,h-3],[w-3,h-3]].map(([x,y])=>{const i=(y*w+x)*4;return [d[i],d[i+1],d[i+2]]});const mask=new Uint8Array(w*h),out=new Uint8ClampedArray(d);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,c=[d[i],d[i+1],d[i+2]],min=Math.min(...cs.map(q=>colorDist(c,q)));let alpha=d[i+3];if(alpha<16||min<t)alpha=0;else if(min<t*1.55)alpha=Math.round(alpha*(min-t)/(t*.55));mask[y*w+x]=alpha>20?255:0;out[i+3]=alpha} // keep biggest connected component approximately via bbox of opaque pixels
state.mask={width:w,height:h,data:mask};state.cutRGBA=new ImageData(out,w,h);drawAnalysisPreviews();mark('cut');log('背景解析を実行しました（ローカル色差方式）')}
function drawAnalysisPreviews(){if(!state.cutRGBA)return;const {width:w,height:h,data}=state.cutRGBA;let minx=w,miny=h,maxx=0,maxy=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){if(data[(y*w+x)*4+3]>20){minx=Math.min(minx,x);miny=Math.min(miny,y);maxx=Math.max(maxx,x);maxy=Math.max(maxy,y)}}if(maxx<=minx){minx=0;miny=0;maxx=w-1;maxy=h-1}const tw=maxx-minx+1,th=maxy-miny+1,tmp=document.createElement('canvas');tmp.width=w;tmp.height=h;tmp.getContext('2d').putImageData(state.cutRGBA,0,0);ctx.cut.clearRect(0,0,128,128);const sc=Math.min(118/tw,118/th),dw=tw*sc,dh=th*sc;ctx.cut.drawImage(tmp,minx,miny,tw,th,(128-dw)/2,128-dh-5,dw,dh);ctx.mask.clearRect(0,0,128,128);ctx.mask.fillStyle='#fff';for(let y=0;y<128;y++)for(let x=0;x<128;x++){const sx=Math.floor(x/128*w),sy=Math.floor(y/128*h);if(state.mask.data[sy*w+sx])ctx.mask.fillRect(x,y,1,1)}}
function kmeansPalette(pixels,k){if(!pixels.length)return state.palette;let cent=[];for(let i=0;i<k;i++)cent.push(pixels[Math.floor(i*(pixels.length-1)/(k-1||1))].slice());for(let it=0;it<8;it++){const sums=Array.from({length:k},()=>[0,0,0,0]);for(const p of pixels){let bi=0,bd=1e9;for(let j=0;j<k;j++){const dd=(p[0]-cent[j][0])**2+(p[1]-cent[j][1])**2+(p[2]-cent[j][2])**2;if(dd<bd){bd=dd;bi=j}}const s=sums[bi];s[0]+=p[0];s[1]+=p[1];s[2]+=p[2];s[3]++}for(let j=0;j<k;j++)if(sums[j][3])cent[j]=sums[j].slice(0,3).map(v=>v/sums[j][3])}return cent.sort((a,b)=>(a[0]+a[1]+a[2])-(b[0]+b[1]+b[2])).map(c=>hex(...c))}
function extractPalette(){if(!state.sourceRGBA)return;const d=state.sourceRGBA.data,p=[];const step=Math.max(1,Math.floor((state.sourceRGBA.width*state.sourceRGBA.height)/20000));for(let i=0;i<d.length;i+=4*step)if(d[i+3]>30)p.push([d[i],d[i+1],d[i+2]]);state.palette=kmeansPalette(p,Math.min(32,+$('colorCount').value||24));state.colorIndex=Math.min(4,state.palette.length-1);renderPalette();log('パレットを抽出しました')}
function nearestPalette(c){let best=rgba(state.palette[0]),bd=1e9;for(const h of state.palette){const q=rgba(h),d=(c[0]-q[0])**2+(c[1]-q[1])**2+(c[2]-q[2])**2;if(d<bd){bd=d;best=q}}return best}
function buildDraft(){if(!state.cutRGBA){autoCut();if(!state.cutRGBA)return}snapshot();state.layers=[];['影','素体','後ろ髪','衣装','袖','顔','耳','前髪','装飾'].forEach(n=>addLayer(n,false));const src=state.cutRGBA,w=src.width,h=src.height,d=src.data;let x0=w,y0=h,x1=0,y1=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>32){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y)}if(x1<=x0){log('人物領域を検出できません');return}const cw=x1-x0+1,ch=y1-y0+1,sc=Math.min(54/cw,60/ch),dw=Math.max(1,Math.round(cw*sc)),dh=Math.max(1,Math.round(ch*sc)),ox=Math.floor((64-dw)/2),oy=63-dh;const temp=document.createElement('canvas');temp.width=w;temp.height=h;temp.getContext('2d').putImageData(src,0,0);const small=document.createElement('canvas');small.width=dw;small.height=dh;const s=small.getContext('2d');s.imageSmoothingEnabled=true;s.drawImage(temp,x0,y0,cw,ch,0,0,dw,dh);const sd=s.getImageData(0,0,dw,dh).data,base=state.layers[1];for(let y=0;y<dh;y++)for(let x=0;x<dw;x++){const i=(y*dw+x)*4;if(sd[i+3]<40)continue;const q=nearestPalette([sd[i],sd[i+1],sd[i+2]]);put(base,ox+x,oy+y,q)}state.activeLayer=1;renderLayers();renderAll();mark('draft');log('64×64初稿を作成しました。次にテンプレート適用・ドット編集を行ってください')}
function findLayer(name){let i=state.layers.findIndex(l=>l.name===name);if(i<0){addLayer(name,false);i=state.layers.length-1}return state.layers[i]}
function clear(l){l.data.fill(0)}
function poly(layer,pts,col){for(let y=0;y<64;y++)for(let x=0;x<64;x++){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const xi=pts[i][0],yi=pts[i][1],xj=pts[j][0],yj=pts[j][1];if(((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi))inside=!inside}if(inside)put(layer,x,y,col)}}
function ellipse(layer,cx,cy,rx,ry,col){for(let y=Math.floor(cy-ry);y<=Math.ceil(cy+ry);y++)for(let x=Math.floor(cx-rx);x<=Math.ceil(cx+rx);x++)if(((x-cx)/rx)**2+((y-cy)/ry)**2<=1)put(layer,x,y,col)}
function template(name){snapshot();const p=state.palette, dark=rgba(p[0]||'#18202a'),hair=rgba(p[Math.min(p.length-1,Math.floor(p.length*.65))]||'#8b87aa'),light=rgba(p[Math.min(p.length-1,Math.floor(p.length*.82))]||'#d4d0e8'),skin=rgba(p[Math.min(p.length-1,Math.floor(p.length*.75))]||'#efc8b5'),green=rgba(p[Math.min(p.length-1,Math.floor(p.length*.35))]||'#285a45'),gold=rgba('#d9a52e');let l;
 if(name==='hairLong'){l=findLayer('後ろ髪');clear(l);ellipse(l,32,19,13,15,hair);poly(l,[[19,18],[17,43],[22,52],[27,29]],hair);poly(l,[[45,18],[47,43],[42,52],[37,29]],hair);l=findLayer('前髪');clear(l);poly(l,[[20,11],[29,7],[43,11],[45,22],[39,18],[36,25],[32,17],[28,25],[25,18],[19,22]],light)}
 if(name==='elfEars'){l=findLayer('耳');clear(l);poly(l,[[20,18],[9,20],[20,25]],skin);poly(l,[[44,18],[55,20],[44,25]],skin)}
 if(name==='wideSleeves'){l=findLayer('袖');clear(l);poly(l,[[22,29],[13,33],[8,48],[15,54],[23,41]],light);poly(l,[[42,29],[51,33],[56,48],[49,54],[41,41]],light)}
 if(name==='torsoSlim'){l=findLayer('衣装');clear(l);poly(l,[[25,27],[39,27],[43,45],[37,51],[27,51],[21,45]],green)}
 if(name==='boots'){l=findLayer('素体');poly(l,[[24,45],[31,45],[29,61],[23,61]],dark);poly(l,[[33,45],[40,45],[41,61],[35,61]],dark)}
 if(name==='gold'){l=findLayer('装飾');clear(l);for(const [x,y] of [[32,28],[29,31],[35,31],[26,39],[30,39],[34,39],[38,39],[25,56],[39,56]])paint(x,y,gold,l)}
 state.activeLayer=state.layers.indexOf(l||state.layers[state.activeLayer]);renderLayers();renderAll();mark('parts');log('部位テンプレートを適用しました: '+name)}
function applyElf(){['hairLong','elfEars','wideSleeves','torsoSlim','boots','gold'].forEach(template);const face=findLayer('顔');clear(face);ellipse(face,32,20,9,10,rgba(state.palette[Math.min(state.palette.length-1,Math.floor(state.palette.length*.72))]||'#efc8b5'));const dark=rgba(state.palette[0]||'#18202a');put(face,28,20,dark);put(face,29,20,dark);put(face,35,20,dark);put(face,36,20,dark);put(face,32,24,rgba('#b86b62'));renderAll();mark('parts');log('エルフ正面テンプレートを適用しました')}
function refreshOutputs(markIt=true){const d=composite();drawData(C.out64,d,64,64);const t=document.createElement('canvas');t.width=64;t.height=64;t.getContext('2d').putImageData(new ImageData(d,64,64),0,0);const c32=C.out32.getContext('2d');c32.imageSmoothingEnabled=false;c32.clearRect(0,0,32,32);c32.drawImage(t,0,0,32,32);const c128=C.out128.getContext('2d');c128.imageSmoothingEnabled=false;c128.clearRect(0,0,128,128);c128.drawImage(t,0,0,128,128);if(markIt)mark('export')}
function frameFrom(base,n){const out=new Uint8ClampedArray(base);if(n===0)return out;const shift=n===1?1:n===2?0:-1;const yShift=n===2?1:0;const res=new Uint8ClampedArray(out.length);for(let y=0;y<64;y++)for(let x=0;x<64;x++){const sy=y-yShift,sx=x-shift;if(sx>=0&&sx<64&&sy>=0&&sy<64){const si=(sy*64+sx)*4,di=(y*64+x)*4;res.set(out.slice(si,si+4),di)}}return res}
function generateFrames(){const base=composite();state.frames=[0,1,2,3].map(i=>frameFrom(base,i));$('frames').innerHTML='';state.frames.forEach((d,i)=>{const c=document.createElement('canvas');c.width=c.height=64;c.getContext('2d').putImageData(new ImageData(d,64,64),0,0);c.title='Frame '+(i+1);$('frames').append(c)});mark('animation');log('待機・歩行用の簡易4フレームを生成しました')}
function downloadCanvas(canvas,name){canvas.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')}
function exportSheet(){if(!state.frames.length)generateFrames();const c=document.createElement('canvas');c.width=256;c.height=64;const x=c.getContext('2d');state.frames.forEach((d,i)=>{const t=document.createElement('canvas');t.width=t.height=64;t.getContext('2d').putImageData(new ImageData(d,64,64),0,0);x.drawImage(t,i*64,0)});downloadCanvas(c,state.projectName+'_sheet.png');mark('export')}
function saveProject(){const obj={version:'1.30.0',name:state.projectName,palette:state.palette,active:state.activeLayer,layers:state.layers.map(l=>({name:l.name,visible:l.visible,data:Array.from(l.data)}))};const b=new Blob([JSON.stringify(obj)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=state.projectName+'.sprite.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function loadProject(file){file.text().then(t=>{const o=JSON.parse(t);state.projectName=o.name||'sprite_project';state.palette=o.palette||state.palette;state.layers=o.layers.map((l,i)=>({id:String(i),name:l.name,visible:l.visible!==false,data:new Uint8ClampedArray(l.data)}));state.activeLayer=Math.min(o.active||0,state.layers.length-1);renderPalette();renderLayers();renderAll();log('プロジェクトを読み込みました')}).catch(e=>log('読込エラー: '+e.message))}
function mirror(){snapshot();const l=state.layers[state.activeLayer],d=new Uint8ClampedArray(l.data);for(let y=0;y<64;y++)for(let x=0;x<64;x++){const s=(y*64+x)*4,t=(y*64+(63-x))*4;l.data.set(d.slice(s,s+4),t)}renderAll()}
function newProject(){snapshot();state.layers=[];ensureLayers();state.workflow.clear();document.querySelectorAll('.step').forEach(e=>e.classList.remove('done'));renderAll();log('新規プロジェクトを作成しました')}
function bind(){ensureLayers();renderPalette();renderAll();$('chooseImageBtn').onclick=()=>$('imageInput').click();$('imageInput').onchange=e=>e.target.files[0]&&loadImage(e.target.files[0]);$('autoCut').onclick=autoCut;$('resetCut').onclick=()=>{state.cutRGBA=null;state.mask=null;ctx.mask.clearRect(0,0,128,128);ctx.cut.clearRect(0,0,128,128);log('解析をリセットしました')};$('bgTolerance').oninput=e=>$('bgToleranceValue').textContent=e.target.value;$('buildDraft').onclick=buildDraft;$('applyElfTemplate').onclick=applyElf;$('extractPalette').onclick=extractPalette;$('addColor').onclick=()=>{state.palette.push($('colorPicker').value);state.colorIndex=state.palette.length-1;renderPalette()};$('brushSize').onchange=e=>state.brush=+e.target.value;$('gridToggle').onchange=renderGrid;document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('.templateBtn').forEach(b=>b.onclick=()=>template(b.dataset.template));document.querySelectorAll('.zoomBtn').forEach(b=>b.onclick=()=>{state.zoom=+b.dataset.zoom;document.querySelectorAll('.zoomBtn').forEach(x=>x.classList.toggle('active',x===b));const px=state.zoom*64;$('canvasStack').style.width=px+'px';$('canvasStack').style.height=px+'px';[C.composite,C.editor,C.grid].forEach(c=>{c.style.width=px+'px';c.style.height=px+'px'})});C.editor.addEventListener('pointerdown',onDown);C.editor.addEventListener('pointermove',onMove);C.editor.addEventListener('pointerup',onUp);C.editor.addEventListener('pointercancel',onUp);$('undo').onclick=doUndo;$('redo').onclick=doRedo;$('mirror').onclick=mirror;$('clearLayer').onclick=()=>{snapshot();clear(state.layers[state.activeLayer]);renderAll()};$('addLayer').onclick=()=>{snapshot();addLayer('レイヤー '+(state.layers.length+1))};$('refreshOutputs').onclick=()=>refreshOutputs();$('generateFrames').onclick=generateFrames;$('exportSheet').onclick=exportSheet;$('export32').onclick=()=>downloadCanvas(C.out32,state.projectName+'_32.png');$('export64').onclick=()=>downloadCanvas(C.out64,state.projectName+'_64.png');$('export128').onclick=()=>downloadCanvas(C.out128,state.projectName+'_128.png');$('saveProject').onclick=saveProject;$('loadProjectBtn').onclick=()=>$('loadProject').click();$('loadProject').onchange=e=>e.target.files[0]&&loadProject(e.target.files[0]);$('newProject').onclick=newProject;$('helpBtn').onclick=()=>alert('1.画像読込→2.背景解析→3.初稿→4.テンプレート→5.ドット編集→6.アニメ→7.保存。iPhoneでは指で直接描けます。');window.SpriteStudioV130={state,autoCut,buildDraft,applyElf,refreshOutputs,generateFrames,saveProject,loadProject,composite};log('Sprite Studio v1.30 準備完了')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
